// index
export const POPUP_DETAIL = 'POPUP_DETAIL'
export const POPUP_MONITOR_CAR_DETAIL = 'POPUP_MONITOR_CAR_DETAIL'
export const CURR_CAR_INFO = 'CURR_CAR_INFO'
// user
export const SET_USER = 'SET_USER'
export const SHOW_TRACK_BACK_PANEL = 'SHOW_TRACK_BACK_PANEL'
export const SHOW_VIDEO_BACK_PANEL = 'SHOW_VIDEO_BACK_PANEL'
export const ALARM_SHOW_TRACK_BACK_PANEL = 'ALARM_SHOW_TRACK_BACK_PANEL'
export const ALARM_SHOW_VIDEO_BACK_PANEL = 'ALARM_SHOW_VIDEO_BACK_PANEL'
export const SET_MAP_LOAD_STATE = 'SET_MAP_LOAD_STATE'
export const ALARM_REAL_TIME_VIDEO = 'ALARM_REAL_TIME_VIDEO'

// map event
export const SET_EVENT_NAME = 'SET_EVENT_NAME'
